// What the folk of the painting say (see folk.ts): each person's first words (their name), an old
// acquaintance's greeting by the way they speak (with {名}, filled at render), and the role templates —
// every crowd figure can be talked to, in words that differ for every companion: their own line, else
// their kind's (@wen 文 · @nong 农 · @wu 武 · @xian 仙 · @shou 兽), else everyone's. Rotated by the day.
import type { CrowdRole } from './lines';
import { L, type Voiced } from './logic';
import type { DLine, Voice } from './folk';

/** A line the walker's companion says. */
export const M = (zh: string, en: string): DLine => ({ zh, en, by: 'me' });

// ───────────────────────────── first words: a name given ─────────────────────────────

export const INTROS: Record<string, DLine> = {
  'v.qingtuan': L('姓方，行大，街坊都叫我方大。这青团的方子，是我娘传下来的。', 'Fang’s the name, the eldest — Fang Da to everyone. The green-cake recipe was my mother’s.'),
  'v.lingjiao': L('我姓王，排行第四，都叫我王四娘。这菱角，是我闺女从湖里采的。', 'Wang, fourth of my family — Wang Siniang, they call me. My daughter picks these chestnuts on the lake.'),
  'v.basket': L('严六。篾匠。（他只顾低头编筐。）', 'Yan Liu. Basket-maker. (He keeps his eyes on the weaving.)'),
  'v.needle': L('我是苏二娘。这条街上谁家有什么事，问我就对了。', 'I’m Su Erniang. Whatever happens on this street, I’m the one to ask.'),
  'v.ou': L('我叫邱二，那边炒栗子的是我爹。白天我卖藕，晚上他卖栗子。', 'Qiu Er. The chestnut man over there is my father — I sell lotus by day, he sells chestnuts by night.'),
  'v.teaegg': L('许三姑！茶叶蛋煮了二十年，镇上的孩子，都是吃我的蛋长大的。', 'Aunt Xu! Twenty years of tea eggs — every child in this town grew up on them.'),
  'v.zheng': L('老朽姓郑，在这茶馆坐了三十年，茶也凉了三十年。', 'Zheng is my name. Thirty years I’ve sat in this teahouse, letting my tea go cold.'),
  'v.mawu': L('马五！下棋么？不下？那坐着看我下。', 'Ma Wu! A game? No? Then sit and watch me play.'),
  'v.pei': L('在下姓裴，从城里来避暑。这里的茶，比城里的好。', 'My name is Pei — up from the city to escape the heat. The tea is better here than in town.'),
  'v.axiu': L('我叫阿秀，这是春燕。我俩天天在这儿捶衣裳，镇上的事，一样也跑不了。', 'I’m A Xiu, and that’s Chunyan. We’re here beating the washing every day — nothing in this town gets past us.'),
  'v.chunyan': L('我、我叫春燕……刚嫁过来的。秀姐什么都跟我说。', 'I-I’m Chunyan… newly married here. Sister Xiu tells me everything.'),
  'v.he': L('何三婶！我家妞妞你见过没？扎两个小辫，跑得比兔子还快。', 'Aunt He! Have you seen my Niuniu? Two little plaits, runs faster than a rabbit.'),
  'v.meng': L('我姓孟，男人在码头扛活。井边凉快，说说话。', 'Meng — my man carries loads at the wharf. It’s cool by the well; let’s talk.'),
  'v.hutou': L('我叫虎头！我是这条街上跑得最快的！', 'I’m Hutou! I’m the fastest on this street!'),
  'v.erya': L('我叫二丫。虎头是我哥……不是亲的。', 'I’m Erya. Hutou’s my brother… not a real one.'),
  'v.shuanzi': L('我、我叫栓子……我娘怕我跑丢了，才起的这个名儿。', 'I-I’m Shuanzi… Mama named me Tether so I wouldn’t run off.'),
  'v.fan': L('老樊。挑了一辈子担子，肩膀比石头还硬。', 'Old Fan. A lifetime under a carrying pole — shoulders harder than stone.'),
  'v.guniang': L('我夫家姓顾，他是秀才，考了三回了。我出来买菜。', 'My husband’s family is Gu — he’s a licentiate, three times at the exams. I’m out for the groceries.'),
  'v.yaosao': L('姚大嫂就是我！我家那口子卖炭，你闻，身上都是炭味儿。', 'Sister Yao, that’s me! My man sells charcoal — smell that? Charcoal all over.'),
  'v.yaoda': L('姚大，卖炭的。冬天找我。', 'Yao Da, charcoal. Come find me in winter.'),
  'v.guxiucai': L('在下顾廷之，忝为秀才，屡试不第，惭愧惭愧。', 'Gu Tingzhi, an unworthy licentiate — failed the exams more than once. How shameful.'),
  'v.nie': L('聂五，从北边来，往南边去。路过，歇歇脚。', 'Nie Wu, from the north, bound south. Just passing — resting my feet.'),
  'v.feng': L('冯。八十二了。这条巷子，比你们谁都老——我比巷子还老。', 'Feng. Eighty-two. This lane is older than any of you — and I’m older than the lane.'),
  'v.suyun': L('……素云。我是绣花的。（她把脸埋进头巾里。）', '…Suyun. I do embroidery. (She tucks her face into her scarf.)'),
  'v.wu': L('吴，打更的。叫我老吴。这镇上的每一夜，都是我一更一更敲过去的。', 'Wu. The watchman. Call me Old Wu. Every night in this town, I’ve knocked it through, watch by watch.'),
  'v.qiao': L('我姓乔，在姐姐家帮工，这就回去。', 'Qiao — I help at my sister’s. Just heading home.'),
  'v.weijiu': L('卫九，扎灯笼的！你看这盏，兔子耳朵还会动！', 'Wei Jiu, lantern-maker! Look at this one — the rabbit’s ears move!'),
  'v.baolao': L('包老三！馄饨皮薄，汤头鲜，夜里就数我这儿暖和。', 'Bao Laosan! Thin wrappers, rich broth — the warmest spot in the night.'),
  'v.luo': L('罗二嫂。圆子是我自己搓的，一个一个，都一样大。', 'Sister Luo. I roll every rice ball myself — each one the same size.'),
  'v.qiulao': L('姓邱。白天卖藕的那个是我儿子，没出息，只会笑。', 'Qiu. The lotus seller by day is my son — good for nothing but grinning.'),
  'v.niuniu': L('我叫妞妞！这是我的兔儿灯！', 'I’m Niuniu! This is my rabbit lantern!'),
  'v.song': L('老夫姓宋，教了一辈子蒙学。镇上认字的，一半是我教的。', 'Song. A lifetime teaching children their letters — half this town learned to read from me.'),
  'v.mengda': L('我姓孟，在码头扛活。晚上陪我屋里的出来走走。', 'Meng — I carry at the wharf. Evenings I walk out with my wife.'),
  'v.shao': L('老邵。撑船的。四十年了，这条河里的每块石头，我都认得。', 'Old Shao. Boatman. Forty years — I know every stone in this river.'),
  'l.hu': L('胡老三，打鱼的。别吵。', 'Hu Laosan, fisherman. Keep it down.'),
  'l.agen': L('阿根……我夜里打鱼，白天睡觉。', 'A Gen… I fish at night and sleep by day.'),
  'l.linger': L('我叫菱儿！我娘在镇上卖菱角，这些都是我采的！', 'I’m Ling’er! My mum sells water chestnuts in town — I pick them all!'),
  'l.wen': L('在下温如玉，这是舍妹温婉。湖上风好，出来走走。', 'Wen Ruyu — and this is my younger sister, Wen Wan. A fine breeze on the lake; we came out for a walk.'),
  'l.wenwan': L('我是温婉……哥哥说话总是文绉绉的，你别笑他。', 'I’m Wen Wan… my brother always talks like a book. Don’t laugh at him.'),
  'l.lin': L('林晚照。……温公子？他、他就在前头。', 'Lin Wanzhao. …Master Wen? He — he’s just ahead.'),
  'm.liaochen': L('贫僧了尘。晨扫山门，夜巡山道。', 'I am Liaochen. I sweep the gate at dawn and walk the paths at night.'),
  'm.liaofan': L('贫僧了凡，出家才三年，台阶还扫不干净。', 'I am Liaofan — three years a monk, and still I can’t sweep the steps clean.'),
  'm.jueming': L('老僧觉明。这木鱼，敲了五十年了。', 'I am Jueming. Fifty years I have struck this wooden fish.'),
  'm.yindaniang': L('我姓殷，跟老头子上山烧香，替儿子求个功名。', 'Yin — I’ve come up with my old man to burn incense for our son’s exams.'),
  'm.yinlao': L('姓殷，庄户人家。儿子在梅岭上读书，我们来替他求求菩萨。', 'Yin, farming folk. Our son studies on the plum ridge; we’ve come to ask the Bodhisattva for him.'),
  'm.lv': L('……吕家的三媳妇。婆婆病了，我来求个平安。', '…Third daughter-in-law of the Lü family. My mother-in-law is ill; I’ve come to pray.'),
  'm.liang': L('梁七姑。白天没空，只好夜里来。', 'Aunt Liang. No time by day, so I come by night.'),
  'p.ouyang': L('老夫欧阳，致仕在家。每年梅开，必来此处。', 'Ouyang, retired from office. Every year when the plum blooms, I come here.'),
  'p.yinsheng': L('小、小生姓殷……爹娘在山寺替我烧香，我在这儿读书。', 'I — I am Yin… my parents are burning incense for me at the temple, and I’m up here studying.'),
  'p.yezhou': L('在下叶舟，一叶扁舟的叶舟。娘子在家，晚上带她来看梅。', 'Ye Zhou — as in “a leaf of a boat”. My wife is at home; tonight I’ll bring her to see the plum.'),
  'p.zhuo': L('卓。夜里看梅，白天不来。', 'Zhuo. I see the plum at night. Never by day.'),
  'p.yeniang': L('我家相公白天来看梅，晚上又拉我来看一遍。', 'My husband sees the plum by day, then drags me up to see it all again by night.'),
  'b.xiang': L('姓向。住在竹林那头，听竹子说话。', 'Xiang. I live at the far end of the grove, listening to the bamboo talk.'),
  'b.tan': L('老谭，挖笋的。春笋冬笋，我闭着眼都挖得着。', 'Old Tan, shoot-digger. Spring shoots, winter shoots — I could find them blindfold.'),
  'b.cai': L('蔡九。砍竹子的。天黑了，回家。', 'Cai Jiu. I cut bamboo. It’s dark. Going home.'),
  'h.geng': L('俺叫耿大郎，就种你隔壁那块地。往后是邻居了！', 'Geng Dalang — I farm the plot next to yours. We’re neighbours now!'),
  'h.gengsao': L('我是耿大嫂！我家那口子话少，有事找我。', 'I’m Sister Geng! My man doesn’t say much — come to me for anything.'),
  'n.peddler': L('我姓孙，行七，挑这副担子走了二十年——叫我孙七就成！', 'Sun, seventh son — twenty years with this pole. Just call me Sun Qi!'),
  'n.storyteller': L('在下姓钱——可惜名不副实。说书为生，客官叫我钱先生便是。', 'Qian is my name — “money”, alas, in name only. I tell stories for a living: call me Master Qian.'),
  'n.fortune': L('老朽姓袁，人送外号「半仙」——另一半，还在修。', 'Yuan. They call me the Half-Immortal — the other half is still in training.'),
  'n.sugar': L('姓张，吹糖人三十年，都叫我糖人张。', 'Zhang — thirty years of blowing sugar. Sugar-Figure Zhang, they call me.'),
  'n.flower': L('我叫杏儿！杏花的杏。', 'I’m Xing’er! As in apricot blossom.'),
  'n.farmer': L('我姓田，种了一辈子田——老天爷给的姓，改不了。', 'My name’s Tian — “field” — and I’ve farmed all my life. Heaven chose it; no changing it.'),
  'n.shutong': L('我叫小篆！先生给起的，说我写字像蚯蚓爬。', 'I’m Xiaozhuan — “Little Seal Script”! Master named me; he says I write like an earthworm.'),
  'n.master': L('在下姓柳，游学四方，带着个不省心的书童。', 'Liu — travelling for learning, with a page boy who keeps me on my toes.'),
  'n.tea': L('小店姓陆，陆羽的陆——祖上这么说，也不知真假。叫我陆掌柜。', 'This house is Lu, as in Lu Yu of the Classic of Tea — so my forebears claimed. Call me Proprietor Lu.'),
  'n.fisher': L('姓江，江上的江。在这渡口，坐了半辈子。', 'Jiang, as in the river. Half my life I’ve sat on this dock.'),
  'n.monk': L('贫僧了缘，在山门知客。施主，有缘。', 'I am Liaoyuan, guest-master at the gate. We were fated to meet.'),
  'n.poet': L('山人无名，住在梅溪边，人称梅溪居士。', 'I have no name worth keeping. I live by the Plum Creek — they call me the Plum Creek Recluse.'),
  'n.kite': L('我叫阿蛮！我娘说我野，跟风筝一样。', 'I’m A’man! Mama says I’m wild, like a kite.'),
};

// ───────────────────────────── 熟客: an old acquaintance's greeting ─────────────────────────────

export const REGULAR: Record<Voice, DLine[]> = {
  plain: [L('{名}，又来啦？坐会儿。', '{名}, back again? Stay a while.'), L('是{名}呀，今儿气色不错。', 'It’s {名}! You look well today.')],
  gossip: [L('哟，{名}！正说到你呢——', 'Oh, {名}! We were just talking about you —'), L('{名}来得巧，我这儿有件新鲜事。', 'Good timing, {名} — I’ve got news.')],
  shy: [L('{名}……你又来了。', '{名}… you came again.'), L('（看见是{名}，笑了一下。）', '(Seeing it’s {名}, a small smile.)')],
  gruff: [L('嗯，{名}。', 'Mm. {名}.'), L('{名}。老地方，老样子。', '{名}. Same place, same as ever.')],
  pious: [L('{名}施主，又见面了。', '{名}, we meet again.'), L('阿弥陀佛，{名}施主来了。', 'Amituofo — {名} has come.')],
  bookish: [L('{名}兄，幸会幸会，又见面了。', '{名}, my friend — well met again.'), L('{名}来了？正好，有一句想请教。', '{名}! Just the person — I have a line to ask you about.')],
  merry: [L('{名}！老主顾来啦！', '{名}! My old regular!'), L('哈哈，{名}，就知道你今天会来。', 'Ha, {名} — I knew you’d come today.')],
  child: [L('{名}！{名}来啦！', '{名}! {名}’s here!'), L('{名}，陪我玩！', '{名}, play with me!')],
};

/** An old acquaintance, passing: a bubble over their head, by name. */
export const HAIL: DLine[] = [L('{名}！', '{名}!'), L('{名}，来啦！', '{名} — hello again!'), L('哟，{名}！', 'Oh — {名}!'), L('{名}，得空坐坐！', '{名}, stop by when you can!')];

// ───────────────────────────── the role templates ─────────────────────────────

type Pool = Voiced<DLine[]>;
export interface RoleTalk { chat: Pool; night?: Pool }

export const ROLE_TALK: Record<CrowdRole, RoleTalk> = {
  villager: {
    chat: {
      any: [L('今儿集上人多，走路当心钱袋。', 'Busy market today — mind your purse.'), L('这水乡啊，桥比路多，船比车多。', 'In this water town there are more bridges than roads, more boats than carts.'), L('打园子那边来的？听说半亩园里的花，一天比一天好。', 'From the garden way? They say the Half-Acre’s flowers get finer by the day.')],
      '@wen': [L('先生是读书人吧？镇东头宋夫子那儿，常有人去借书。', 'A man of letters? Old Master Song at the east end lends out books.'), L('读书人来得正好，帮我看看这张纸写的什么？……哦，是借据。', 'A reader — just the one. What does this paper say? …Oh. It’s an IOU.')],
      '@nong': [L('看您这手，是干活的手。今年的秧苗怎么样？', 'Those are working hands. How are this year’s seedlings?'), L('同是靠天吃饭的人，打个招呼！', 'We both live by the weather — good day to you!')],
      '@wu': [L('好威风！有您在，镇上的小毛贼都不敢出门了。', 'What bearing! With you about, the petty thieves won’t dare step out.'), L('前两天桥头有人打架，您要是在就好了。', 'There was a brawl at the bridgehead the other day. Wish you’d been there.')],
      '@xian': [L('您……走路怎么没声儿？', 'You… how do you walk without a sound?'), L('您看着不像凡人，莫不是画里走出来的？', 'You don’t look of this world. Stepped out of a painting, did you?')],
      '@shou': [L('哪家的……咦，自己走来的？', 'Whose is this… oh, it came by itself?'), L('乖乖，过来，给你一块糕。', 'Come here, sweetheart — have a bit of cake.')],
      scholar: [L('赶考的么？我们镇上出过一个探花呢，就住桥那边。', 'Off to the exams? Our town once had a Tanhua — third in the palace exam. He lived over the bridge.')],
      poet: [L('太白先生！镇上酒家的酒旗，都为您换了新的。', 'Master Li Bai! Every tavern in town has hung out a new wine flag for you.')],
      painter: [L('画师，我们这桥、这船、这柳树，画得下么？', 'Painter — our bridges, our boats, our willows: can you fit them all in?')],
      player: [L('棋士来了！茶馆里马五天天摆着棋盘等人，您去杀他一盘。', 'The go master! Ma Wu sets out a board at the teahouse every day — go and beat him.')],
      musician: [L('是琴师呀！前天夜里桥上有人弹琴，是不是您？', 'The qin player! Was that you playing on the bridge the other night?')],
      gardener: [L('园丁师傅，我家门口那棵石榴不结果，您给瞧瞧？', 'Gardener, the pomegranate by my door won’t fruit. Would you take a look?')],
      fisher: [L('老哥，今儿河里的鱼，都往您那边游。', 'Old man, every fish in the river is swimming your way today.')],
      swordsman: [L('大侠，您这剑……能借我看看么？就看一眼！', 'Hero, that sword… may I look? Just one look!')],
      guan: [L('（连忙作揖）关老爷！小人给您请安了！', '(Bowing hastily) Lord Guan! Your humble servant greets you!')],
      taoist: [L('小道长，我家灶王爷最近脾气不好，饭总烧糊。', 'Little Taoist, my kitchen god’s been cross lately — the rice keeps burning.')],
      change: [L('……（看呆了半晌）您、您是天上下来的吧？', '…(A long stare.) You — you’ve come down from the sky, haven’t you?')],
      rabbit: [L('哎呀，白白净净的小兔子，是月亮上掉下来的？', 'Oh my, what a clean white bunny — did you fall off the moon?')],
      cat: [L('大橘！又是你！昨天偷了谁家的鱼？', 'Big Ginger! You again! Whose fish did you steal yesterday?')],
    },
    night: {
      any: [L('这么晚还在外头？早些回去。', 'Out so late? Get along home.'), L('月亮出来了，河上亮堂堂的。', 'The moon’s up — the river’s all silver.')],
      '@xian': [L('夜里遇见您，倒像做了个好梦。', 'Meeting you at night is like a good dream.')],
      '@shou': [L('夜猫子！……哦，是只真猫。', 'A night owl! …Oh — a real cat.')],
      '@wen': [L('夜读的人也出来透气了？', 'A night reader out for some air?')],
      '@nong': [L('忙了一天，夜里走走，腿脚松快。', 'A walk at night after a day’s work loosens the legs.')],
      '@wu': [L('有您在，夜路也安稳。', 'With you about, the night road feels safe.')],
    },
  },
  vendor: {
    chat: {
      any: [L('客官看看，不买也看看！', 'Have a look, friend — no need to buy!'), L('今儿的货新鲜，明儿可就不一定了。', 'Fresh today; tomorrow, who knows.')],
      '@wen': [L('读书人买东西，我给您算便宜些——回头写副对子给我挂摊上。', 'For a man of letters, a better price — just write me a couplet for my stall some day.')],
      '@nong': [L('都是自家地里出的，您一看就知道好坏。', 'All from our own land — you can tell good from bad at a glance.')],
      '@wu': [L('这位爷，东西随便挑，就是别在摊前舞刀弄剑。', 'Pick what you like, sir — only no swordplay in front of the stall.')],
      '@xian': [L('仙家也逛集？那我可得把最好的摆前头。', 'Immortals go to market too? Then the best goes out in front.')],
      '@shou': [L('去去，别蹭我的筐……好吧，蹭一下。', 'Shoo, don’t rub against my baskets… oh, all right, one rub.')],
      cat: [L('大橘，我这儿可没有鱼。……真没有。', 'Big Ginger, there’s no fish here. …Honestly.')],
      guan: [L('关、关老爷！您要什么，小的双手奉上！', 'L-Lord Guan! Whatever you want, it’s yours!')],
    },
  },
  tea: {
    chat: {
      any: [L('坐，坐。这茶馆的茶，要慢慢喝。', 'Sit, sit. The tea here is to be drunk slowly.'), L('听说了么？荷塘边上夜里有盏灯，一闪一闪的。', 'Heard? There’s a lamp out on the lotus pond at night, flickering.'), L('马五又输了棋，赖着不肯走。', 'Ma Wu’s lost at chess again and won’t leave.')],
      '@wen': [L('来来，正缺个评理的：「疏影横斜」的下一句，是「暗香浮动」吧？', 'Come, we need a judge: after “sparse shadows slant”, it’s “faint fragrance drifts”, isn’t it?')],
      '@nong': [L('歇歇脚，喝碗粗茶，比什么都解乏。', 'Rest your feet — a bowl of plain tea beats anything for tiredness.')],
      '@wu': [L('壮士喝茶？茶馆的碗小，您别嫌。', 'Tea for a warrior? The bowls here are small — don’t mind.')],
      '@xian': [L('这位喝茶么？还是……喝露水？', 'Tea for you? Or… do you drink dew?')],
      '@shou': [L('嘘——桌子底下有只猫，在偷听。', 'Shh — there’s a cat under the table, listening.')],
      player: [L('棋士！快来，马五这盘棋，我看是没救了。', 'Go master! Quick — I think Ma Wu’s game is beyond saving.')],
      musician: [L('琴师若肯在这儿弹一曲，这壶茶我请。', 'If the qin player would play here, this pot’s on me.')],
    },
    night: {
      any: [L('天黑了还不回家，说明这茶好。', 'Still here after dark — that’s how good the tea is.'), L('夜里的茶馆，说的话比白天多，也比白天真。', 'At night the teahouse talks more, and more truly.')],
      '@wu': [L('夜里路黑，壮士送我们一程？', 'Dark roads tonight — would a warrior see us home?')],
      '@xian': [L('夜里有神仙来喝茶，明儿说出去，没人信。', 'An immortal at tea by night — no one will believe me tomorrow.')],
      '@wen': [L('夜深了，正好对一句：「灯前一局棋」——下句？', 'Late enough for a couplet: “A game of go by lamplight” — and the next line?')],
      '@nong': [L('这么晚还不歇？喝口热茶暖暖。', 'Not resting yet? A hot cup to warm you.')],
      '@shou': [L('夜里的猫，眼睛像两盏小灯。', 'A cat at night — eyes like two little lamps.')],
    },
  },
  washer: {
    chat: {
      any: [L('砰、砰——这件褂子，得捶一百下才干净。', 'Thwack — this jacket needs a hundred blows to come clean.'), L('河水凉，心里热乎就行。', 'Cold water — a warm heart makes up for it.')],
      '@wen': [L('读书人也来河边？当心别把书掉水里。', 'A scholar by the river? Don’t drop your book in.')],
      '@nong': [L('你那身衣裳沾了泥，脱下来，我顺手给你捶两下。', 'There’s mud on your clothes — take it off and I’ll give it a beat or two.')],
      '@wu': [L('哟，好大的个子，河对岸都照得见影子。', 'My, so tall — your shadow reaches the far bank.')],
      '@xian': [L('这衣裳的料子，不像咱这儿的布。', 'That cloth — it isn’t from round here.')],
      '@shou': [L('别往水里跳！……哎呀，溅我一身。', 'Don’t jump in the water! …Oh, now I’m soaked.')],
      change: [L('仙子的衣裳，是在天河里洗的吧？', 'Fair lady, do you wash your clothes in the River of Heaven?')],
    },
  },
  child: {
    chat: {
      any: [L('你来当老鹰，我们当小鸡！', 'You be the hawk, we’ll be the chicks!'), L('我能一口气跑三圈！你信不信？', 'I can run three laps in one go! Don’t you believe me?')],
      '@wen': [L('先生，你会写「虎」字么？我只会写一半。', 'Mister, can you write “tiger”? I can only do half.')],
      '@nong': [L('你身上有青草的味道！', 'You smell of grass!')],
      '@wu': [L('哇！真刀！能不能教我一招？', 'Wow! A real blade! Teach me one move?')],
      '@xian': [L('你会飞吗？飞一个给我看看！', 'Can you fly? Fly for me!')],
      '@shou': [L('让我摸摸！就一下！', 'Let me pet you! Just once!')],
    },
    night: {
      any: [L('娘说天黑了要回家……再玩一会儿嘛。', 'Mama says come home when it’s dark… just a little longer.')],
      '@xian': [L('月亮上的人，你看得见我的灯吗？', 'Moon person, can you see my lantern?')],
      '@wen': [L('先生，天上那颗最亮的星叫什么？', 'Mister, what’s the brightest star called?')],
      '@nong': [L('萤火虫！你看，那边有萤火虫！', 'Fireflies! Look — fireflies over there!')],
      '@wu': [L('有你在，我不怕黑！', 'With you here I’m not scared of the dark!')],
      '@shou': [L('你的眼睛在夜里会发光！', 'Your eyes shine in the dark!')],
    },
  },
  boatman: {
    chat: {
      any: [L('坐船么？这条河，我撑了四十年。', 'A ride? I’ve poled this river forty years.'), L('桥洞低，船过的时候，要低头。', 'The bridges are low — duck when we pass under.')],
      '@wen': [L('读书人坐我的船，总要吟两句。你也来两句？', 'Scholars in my boat always recite a line or two. You too?')],
      '@nong': [L('你我都是看天吃饭的，水涨水落，心里有数。', 'We both live by the sky — we know when the water rises.')],
      '@wu': [L('这位坐稳些，船小，经不起您一跺脚。', 'Sit steady, sir — a small boat can’t take one of your stamps.')],
      '@xian': [L('您要是会踏水，还坐什么船呐。', 'If you can walk on water, why take a boat?')],
      '@shou': [L('上船可以，别抓我的斗笠。', 'Aboard you come — just don’t claw my hat.')],
    },
    night: {
      any: [L('夜里撑船，认的是桥上的灯。', 'Poling at night, I steer by the lanterns on the bridges.')],
      '@xian': [L('夜里的河，天上一条，水里一条，我撑的是哪条？', 'At night there are two rivers, one above and one below — which am I poling?')],
      '@wen': [L('夜里坐船，最好吟一句「夜泊」。', 'On a boat at night, the thing is to recite a “Night Mooring”.')],
      '@nong': [L('夜里水凉，船头坐稳。', 'The water’s cold at night — sit steady at the bow.')],
      '@wu': [L('夜里有您押船，我连灯都不用挂了。', 'With you guarding the boat, I hardly need the lamp.')],
      '@shou': [L('船头那盏灯，别扑。', 'That lamp at the bow — no pouncing.')],
    },
  },
  fisher: {
    chat: {
      any: [L('嘘……鱼听得见。', 'Shh… the fish can hear.'), L('荷叶底下最凉快，鱼都躲那儿。', 'Under the lotus leaves is coolest — that’s where the fish hide.')],
      '@wen': [L('读书人也钓鱼？钓鱼跟读书一个理——要坐得住。', 'Scholars fish? It’s like reading: you have to sit still.')],
      '@nong': [L('同行！今儿水清，鱼精。', 'A fellow of the trade! Clear water today — the fish are canny.')],
      '@wu': [L('大侠，你往这儿一站，鱼都吓跑了。', 'Hero, you stand there and every fish flees.')],
      '@xian': [L('湖上起雾的时候，常见有人在水面上走——就是您吧？', 'When the mist rises I often see someone walking on the water — that was you, wasn’t it?')],
      '@shou': [L('别盯着我的鱼篓！', 'Stop eyeing my creel!')],
      scholar: [L('书生，你看这湖，像不像一页还没写字的纸？', 'Scholar, look at the lake — like a page with nothing written on it yet?')],
      poet: [L('太白先生，「垂钓坐磐石，水清心亦闲」——是您写的吧？', 'Master Li — “Fishing on a flat stone, the water clear, the heart at ease”: that’s yours, isn’t it?')],
      painter: [L('画师，把我画进去，斗笠要画大些。', 'Painter, put me in — and make the hat bigger.')],
      player: [L('下棋的也来了？钓鱼跟下棋一样，先动的输。', 'The go player? Fishing’s like your game — whoever moves first loses.')],
      musician: [L('琴师，你在船上弹一曲，鱼会不会浮上来听？', 'Qin player, if you played on the boat, would the fish rise to listen?')],
      gardener: [L('园丁，你们种花的也会看天？明儿有雨没有？', 'Gardener — you flower people read the sky too? Rain tomorrow?')],
      fisher: [L('老伙计！你那根竿子还是那根竿子，我这根还是这根。哈哈。', 'Old friend! Your rod’s the same rod, and mine’s the same. Ha!')],
      swordsman: [L('侠客，剑收一收，湖上反光，晃得鱼不咬钩。', 'Swordsman, sheathe it — the glint off the water puts the fish off.')],
      guan: [L('关将军！当年水淹七军，这湖里的鱼都还记着您呢。', 'Lord Guan! The fish of this lake still remember the seven armies you drowned.')],
      taoist: [L('小道长，给我画张「鱼上钩」的符！', 'Little Taoist, draw me a “fish on the hook” charm!')],
      change: [L('……（他看了看你，又看了看水里的月亮）怪了，两个一样好看。', '…(He looks at you, then at the moon in the water.) Strange — both equally lovely.')],
      rabbit: [L('小兔子，月亮上没有湖吧？来，坐我船头。', 'Little rabbit, no lakes on the moon, eh? Come, sit at my bow.')],
      cat: [L('你这馋猫——一条小的，就一条！', 'You greedy cat — one small one. Just one!')],
    },
    night: {
      any: [L('夜里的鱼，是跟着灯来的。', 'At night the fish come to the lamp.'), L('湖上静，连荷叶翻身都听得见。', 'The lake’s so still you can hear a lotus leaf turn over.')],
      '@xian': [L('夜里湖上有两个月亮，一个在天上，一个在船边。', 'At night there are two moons on the lake — one above, one by the boat.')],
      cat: [L('夜里也来？……喏，这条小的，趁热。', 'Here at night too? …There — the little one, while it’s fresh.')],
      '@wen': [L('月下垂钓，钓的是月亮。', 'Fishing by moonlight, you catch the moon.')],
      '@nong': [L('夜里鱼咬钩轻，你得用手指去听。', 'At night the fish bite softly — you have to listen with your fingers.')],
      '@wu': [L('嘘——夜里说话，声音传得远。', 'Shh — at night voices carry far.')],
      '@shou': [L('夜里也来讨鱼？……一条，就一条。', 'Begging fish at night too? …One. Just one.')],
    },
  },
  farmer: {
    chat: {
      any: [L('春种一粒粟，秋收万颗子——前提是不偷懒。', 'Sow one grain in spring, reap ten thousand in autumn — if you don’t slack.'), L('今年雨水匀，是个好年景。', 'The rain’s come evenly this year — a good year.'), L('地是不会骗人的：你给它多少，它还你多少。', 'The land never cheats: what you give it, it gives back.')],
      '@wen': [L('读书人，下地试试？一锄头下去，比写一篇文章还累。', 'Try the field, scholar? One swing of the hoe is harder than an essay.')],
      '@nong': [L('同是种地的！你那边的土，是黄的还是黑的？', 'A fellow farmer! Your soil — yellow or black?')],
      '@wu': [L('这把力气，一天能开两亩荒！', 'With that strength you could break two acres a day!')],
      '@xian': [L('神仙也吃五谷么？……那我多种些。', 'Do immortals eat grain too? …Then I’ll plant more.')],
      '@shou': [L('别踩我的秧！……唉，踩就踩吧，轻点。', 'Mind my seedlings! …Oh, fine — just step lightly.')],
      scholar: [L('书生，「锄禾日当午」背得出，锄头可会拿？', 'Scholar, you can recite “Hoeing at noon”, but can you hold a hoe?')],
      poet: [L('太白先生，给咱地头题首诗，保佑来年丰收。', 'Master Li, write a poem at the field’s edge for next year’s harvest.')],
      painter: [L('画师，把这片田画下来，秋天金黄的时候，再来画一张。', 'Painter, paint this field now — and come again when it’s gold in autumn.')],
      player: [L('棋士，种地跟下棋一样，一步错，一季空。', 'Go master, farming’s like your game: one wrong move and the season’s lost.')],
      musician: [L('琴师，你那琴声一响，牛都不走了。', 'Qin player, when you play, the ox stops in its tracks.')],
      gardener: [L('园丁，你伺候花，我伺候庄稼，都是伺候别人的活儿。', 'Gardener, you tend flowers and I tend crops — both of us waiting on others.')],
      fisher: [L('老哥，你靠水，我靠地，今年都不赖。', 'You live off the water, I off the land — a fair year for both of us.')],
      swordsman: [L('侠客，砍柴比砍人好——柴砍了还能长。', 'Swordsman, better to cut wood than men — wood grows back.')],
      guan: [L('（放下锄头，深深一揖）关老爷，今年庄稼好，托您的福。', '(He sets down the hoe and bows deep.) Lord Guan — a good crop this year, by your grace.')],
      taoist: [L('小道长，你们道家讲「顺天」，我们种地也讲顺天。', 'Little Taoist, your Way says follow heaven; so does farming.')],
      change: [L('仙子……（手里的锄头掉了）月亮上，也种桂花吧？', 'Fair lady… (the hoe slips from his hand) do they grow osmanthus on the moon?')],
      rabbit: [L('兔子！……罢了罢了，你吃惯了月亮上的草，我这地里的，就当请客。', 'A rabbit! …Oh, never mind — you’re used to moon grass. Mine’s on the house.')],
      cat: [L('大橘，替我看着田鼠，秋后给你一条腊鱼。', 'Big Ginger, keep the field mice off and there’s a cured fish for you after harvest.')],
    },
    night: {
      any: [L('天黑了，该回家吃饭了。你也早些歇着。', 'It’s dark — time for supper. Get some rest yourself.')],
      '@nong': [L('看这天色，明早有露水，秧苗要喝饱了。', 'By the look of the sky there’ll be dew by morning — the seedlings will drink their fill.')],
      '@xian': [L('夜里走路，您倒不用灯。', 'You don’t need a lantern at night, it seems.')],
      '@wen': [L('读书人夜里还在外头？「带月荷锄归」，说的就是我。', 'A reader out at night? “Home by moonlight with my hoe” — that’s me.')],
      '@wu': [L('夜里田边有野猪，有您在，我就放心回家了。', 'Wild boar come to the fields at night; with you here I can go home easy.')],
      '@shou': [L('夜里别钻我的地，田鼠的洞多。', 'Don’t go burrowing in my field at night — it’s full of mouse holes.')],
    },
  },
  monk: {
    chat: {
      any: [L('阿弥陀佛。施主，山路陡，慢慢走。', 'Amituofo. The path is steep, friend — go slowly.'), L('扫的是落叶，也是心上的尘。', 'I sweep the fallen leaves — and the dust on the heart.')],
      '@wen': [L('施主是读书人，藏经阁的书，可以借看。', 'You are a reader — the sutra library will lend you books.')],
      '@nong': [L('寺后有块菜地，施主若懂，给指点指点。', 'There’s a vegetable patch behind the temple; if you know the craft, advise us.')],
      '@wu': [L('施主身上杀气重，在佛前站一会儿，就轻了。', 'There’s the weight of battle on you; stand before the Buddha a while and it lightens.')],
      '@xian': [L('施主不似尘中人。贫僧眼拙，莫怪。', 'You do not seem of the dusty world. Forgive a monk’s poor eyes.')],
      '@shou': [L('众生平等。来，这块素饼给你。', 'All beings are equal. Here — a plain cake for you.')],
      scholar: [L('书生施主，书读到头，也是一个「空」字。', 'Scholar, read to the very end and you reach one word: emptiness.')],
      poet: [L('李施主，山门内禁酒，您的葫芦……贫僧替您保管。', 'Master Li, no wine within the gate — your gourd… I’ll keep it for you.')],
      painter: [L('画师施主，大殿的壁画褪了色，您若有心……', 'Painter, the murals in the hall have faded; if you have the heart…')],
      player: [L('棋士施主，觉明师叔棋下得好，就是从来不赢。', 'Go master, Elder Jueming plays well — yet never wins.')],
      musician: [L('琴师施主，晚课时若有琴声，佛也要多听一会儿。', 'Qin player, if there were music at evening prayers, even the Buddha would listen longer.')],
      gardener: [L('园丁施主，寺里那株老银杏快三百岁了，您看它还好么？', 'Gardener, our old ginkgo is nearly three hundred — is it well?')],
      fisher: [L('渔翁施主，放生池里的鱼，可钓不得。', 'Fisherman, the fish in the release pond are not for catching.')],
      swordsman: [L('侠客施主，剑可以挂在山门；心里的那把，也挂一挂。', 'Swordsman, hang your sword at the gate — and the one in your heart, too.')],
      guan: [L('阿弥陀佛——伽蓝护法！贫僧给您上香。', 'Amituofo — the temple’s guardian! Let me light incense for you.')],
      taoist: [L('道友来了。佛道同源，吃碗斋饭再走。', 'A friend of the Way. Buddhists and Taoists share a source — eat before you go.')],
      change: [L('……阿弥陀佛。色即是空，空即是色……（扫帚停了）', '…Amituofo. Form is emptiness, emptiness is form… (the broom stops)')],
      rabbit: [L('月宫的玉兔？经里说，兔子曾舍身供养仙人。', 'The Moon Rabbit? The sutras say a hare once gave itself to feed a sage.')],
      cat: [L('寺里的猫，都是吃斋的。你……吃么？', 'The temple cats all eat vegetarian. Do you?')],
    },
    night: {
      any: [L('夜深了，施主早些下山，莫在林子里迷了路。', 'It’s late — go down soon, and don’t lose your way in the woods.')],
      '@xian': [L('夜里山上常有些说不清的光。施主看见了，莫声张。', 'At night odd lights move on the mountain. If you see them, say nothing.')],
      '@wu': [L('夜巡山道，有施主同行，贫僧的灯也亮些。', 'Walking the night paths with you, my lantern seems brighter.')],
      '@wen': [L('夜里的钟声，要用心听，不要用耳朵。', 'Listen to the night bell with your heart, not your ears.')],
      '@nong': [L('夜露重，施主当心鞋湿。', 'The night dew is heavy — mind your shoes.')],
      '@shou': [L('夜里的山，是你们的。贫僧只是借道。', 'The mountain at night belongs to your kind. I only borrow the path.')],
    },
  },
  woodfish: {
    chat: {
      any: [L('（笃、笃、笃……老僧没有抬头）坐。', '(Tok, tok, tok… the old monk doesn’t look up.) Sit.'), L('木鱼昼夜不闭眼，是叫人莫睡着。', 'The wooden fish never shuts its eyes — to keep us from sleeping.')],
      '@wen': [L('读书人问为何敲木鱼——鱼不闭眼，修行人也莫闭眼。', 'You ask why we strike a fish: fish never close their eyes, and nor should one who practises.')],
      '@nong': [L('敲木鱼跟种地一样，一下一下，急不得。', 'Like farming — one stroke at a time, no hurrying.')],
      '@wu': [L('施主的手，握惯了兵器。握一回木槌试试？', 'Your hands are used to weapons. Try holding the mallet.')],
      '@xian': [L('你听这一声，和上一声，一样么？', 'Listen — this stroke and the last: are they the same?')],
      '@shou': [L('这不是真鱼。……你别舔。', 'It isn’t a real fish. …Don’t lick it.')],
    },
  },
  scholar: {
    chat: {
      any: [L('疏影横斜水清浅，暗香浮动月黄昏——此地正合此句。', '“Sparse shadows slant over clear shallows; faint fragrance drifts in the dusk moon” — this very place.'), L('梅要看瘦的，不看肥的；看斜的，不看正的。', 'In plum, admire the lean, not the plump; the slanting, not the straight.')],
      '@wen': [L('同道！方才得了一句，下联却对不上，兄台帮我想想。', 'A kindred soul! I have a line and can’t match it — help me think.')],
      '@nong': [L('你是种花的？那你说，这梅花，何时浇水最好？', 'You grow things? Then tell me — when is best to water plum?')],
      '@wu': [L('梅花傲雪，将军傲骨，都是一样的。', 'The plum defies the snow; a general’s spine the same.')],
      '@xian': [L('您身上有一股梅香……不，比梅香还清。', 'There’s a plum scent about you… no — clearer than plum.')],
      '@shou': [L('别扒梅树！花瓣都给你摇下来了。', 'Don’t scratch the plum tree! You’re shaking the petals down.')],
      scholar: [L('兄台也来寻梅？梅岭上的诗碑，第三块最好。', 'Seeking plum too, my friend? Of the poem steles up here, the third is best.')],
      poet: [L('太白先生！「梅」字您写得少，今日破个例？', 'Master Li! You wrote little of plum — make an exception today?')],
      painter: [L('画梅要留白，您一定懂的。', 'Painting plum is all in the white you leave — you would know.')],
      player: [L('下棋的也爱梅？这梅枝横斜，倒像一盘乱棋。', 'A go player who loves plum? Those crossing branches look like a tangled game.')],
      musician: [L('《梅花三弄》，您弹得么？就在这儿，弹一弄也好。', 'Can you play “Three Variations on Plum Blossom”? Even one variation, here?')],
      gardener: [L('园丁，这株老梅去年差点冻死，今年反倒开得最好。', 'Gardener, this old plum nearly froze last year — and this year it blooms best of all.')],
      fisher: [L('渔翁也上山来了？「孤舟蓑笠翁，独钓寒江雪」——雪里也有梅呀。', 'The fisherman up the ridge? “A straw-caped old man in a lone boat, fishing the snowy river” — and in the snow there’s plum.')],
      swordsman: [L('侠客，梅下舞剑，花落剑上，这才叫风流。', 'Swordsman — a sword dance under the plum, petals falling on the blade: that is style.')],
      guan: [L('关将军！在下斗胆，请将军为这梅林题一个字。', 'Lord Guan! I make bold to ask a single word from you for this grove.')],
      taoist: [L('小道长，梅妻鹤子的林和靖，也算半个神仙吧？', 'Little Taoist — Lin Bu, with a plum for a wife and cranes for sons: half an immortal, surely?')],
      change: [L('月下看梅，梅在月里……您在梅里。', 'Plum by moonlight, the plum in the moon… and you among the plum.')],
      rabbit: [L('兔子也来赏梅？梅下有雪，雪像月宫。', 'A rabbit come to see the plum? There’s snow beneath, like the moon palace.')],
      cat: [L('猫！梅花底下打盹，倒是懂得风雅。', 'A cat! Napping under plum — you do know elegance.')],
    },
    night: {
      any: [L('夜里看梅，看的是香，不是花。', 'Plum at night: it’s the scent you look at, not the flower.')],
      '@xian': [L('月白，梅白，您也白……分不清了。', 'White moon, white plum, and you in white… I can’t tell them apart.')],
      '@wen': [L('灯下看梅，影子比花好看。', 'Plum by lantern — the shadows are lovelier than the flowers.')],
      '@nong': [L('夜里梅树也歇着，别摇它。', 'The plum rests at night too — don’t shake it.')],
      '@wu': [L('夜里梅岭风大，将军的披风，倒像一面旗。', 'The ridge is windy at night — your cloak flies like a banner.')],
      '@shou': [L('夜里的梅林里，有你一双亮眼睛。', 'In the plum grove at night — a pair of bright eyes: yours.')],
    },
  },
  pilgrim: {
    chat: {
      any: [L('还有几级台阶……菩萨在上头等着呢。', 'How many more steps… the Bodhisattva’s waiting at the top.'), L('心诚则灵。你也来上香的？', 'Sincerity is answered. Have you come to pray too?')],
      '@wen': [L('读书人上山，是求功名吧？', 'A scholar up the mountain — praying for the exams?')],
      '@nong': [L('求个风调雨顺，比什么都要紧。', 'Good wind and rain — that’s the prayer that matters.')],
      '@wu': [L('将军也拜佛？佛前的香，今儿可旺了。', 'A general praying? The incense will burn bright today.')],
      '@xian': [L('你身上有香火味，莫不是庙里出来的？', 'You smell of incense — did you come out of a temple?')],
      '@shou': [L('这是庙里养的么？还是……菩萨派来的？', 'The temple’s pet? Or… sent by the Bodhisattva?')],
    },
    night: {
      any: [L('夜里上山的人，求的都是不好说出口的事。', 'Those who climb by night pray for things they can’t say aloud.')],
      '@xian': [L('您也是夜里来求什么的？……不，您不像是求人的。', 'Have you come by night to ask for something too? …No — you don’t look like one who asks.')],
      '@wen': [L('夜里的山路，一步一个念头。', 'On a mountain path at night, every step is a thought.')],
      '@nong': [L('白天忙地里，夜里才有空来拜。', 'Busy in the fields all day — only at night do I have time to pray.')],
      '@wu': [L('夜路有您，我就不怕了。', 'With you on the night path, I’m not afraid.')],
      '@shou': [L('夜里上山，还有只小东西陪着——也好。', 'Climbing at night with a little creature for company — that’s nice.')],
    },
  },
  watchman: {
    chat: {
      any: [L('天干物燥，小心火烛——你也早些回吧。', 'Dry weather, mind your candles — and get yourself home.'), L('一更人，二更火，三更鬼，四更贼……五更鸡叫，才算过去一夜。', 'First watch folk, second fires, third ghosts, fourth thieves… and at the fifth the cock crows and the night is done.')],
      '@wen': [L('读书人夜里还不睡？当心熬坏了眼睛。', 'A scholar still up? Mind your eyes.')],
      '@nong': [L('这么晚还在外头？地里的活儿，明早再干。', 'Out so late? The fields will keep till morning.')],
      '@wu': [L('有您这样的在，我这梆子都敲得响些。', 'With someone like you about, my clapper rings louder.')],
      '@xian': [L('你……是人吧？夜里我见得多了，得问一句。', 'You… are a person? I see all sorts at night — I have to ask.')],
      '@shou': [L('半夜三更，猫儿狗儿也不睡？', 'Past midnight and still the beasts are up?')],
    },
  },
  lantern: {
    chat: {
      any: [L('夜深了，慢些走。', 'It’s late — go gently.'), L('灯照得见脚下，照不见前头——一步一步走就是了。', 'A lantern shows your feet, not the road ahead — just take it step by step.'), L('河上也有灯，你看，一盏跟着一盏。', 'Lanterns on the river too — look, one after another.')],
      '@wen': [L('月色好，灯也好，该有一首诗。', 'Fine moon, fine lanterns — there ought to be a poem.')],
      '@nong': [L('明儿还要早起，看完这圈灯就回去。', 'Up early tomorrow — one more round of lanterns and home.')],
      '@wu': [L('有您走在前头，夜路也不怕了。', 'With you walking ahead, the night road holds no fear.')],
      '@xian': [L('您身上……好像也有光。', 'You… seem to glow a little yourself.')],
      '@shou': [L('这是谁家的灯笼成了精？', 'Whose lantern has turned into a sprite?')],
      rabbit: [L('兔儿灯！……咦，这只是真的。', 'A rabbit lantern! …Oh — this one’s real.')],
    },
  },
  snack: {
    chat: {
      any: [L('夜宵嘞——暖暖身子！', 'A late bite — warm you right up!'), L('来一碗？不好吃不要钱……不过都说好吃。', 'A bowl? Free if it’s no good… but everyone says it’s good.')],
      '@wen': [L('读书人熬夜，来碗热的，文章都顺些。', 'Scholars up late — something hot and the essay flows.')],
      '@nong': [L('干了一天活，吃口热的，比什么都强。', 'After a day’s work, a hot bite beats everything.')],
      '@wu': [L('这位爷饭量大吧？给您盛满满一大碗。', 'A big appetite, sir? I’ll fill it to the brim.')],
      '@xian': [L('神仙吃不吃夜宵？……闻一闻也是好的。', 'Do immortals eat late? …A sniff will do you good.')],
      '@shou': [L('汤底的骨头，给你留着呢。', 'I’ve kept the bone from the broth for you.')],
      poet: [L('太白先生，酒酿圆子，酒是真酒！', 'Master Li — rice balls in wine, and real wine at that!')],
    },
  },
};
