// Generated by scripts/build_fonts.py (`npm run fonts`) — do not edit by hand.
// A character from wenkai-mirror.woff2: loading it fetches the mirror's own WenKai file.
export const WENKAI_MIRROR_SAMPLE = '';
