// Generated by scripts/build_fonts.py (`npm run fonts`) — do not edit by hand.
// A character from wenkai-walk.woff2: loading it fetches the walk's own WenKai file.
export const WENKAI_WALK_SAMPLE = '丈';
